### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [ovwane/ovwane.github.io#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`index.html`](https://github.com/ovwane/ovwane.github.io/blob/f36c6f129f67c2cd107919f32ad6cd88618fe418/page/19/index.html). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by ovwane** [comment]
Thanks.

**Comment by ovwane** [comment]
> Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`index.html`](https://github.com/ovwane/ovwane.github.io/blob/f36c6f129f67c2cd107919f32ad6cd88618fe418/page/19/index.html). This domain expired a few years ago and is not controlled by Homebrew anymore.
> 
> When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.
> 
> Thank you,
> the Homebrew team.

Thanks.
